[package]
name = "pulse_cdt"
version = "0.1.0"
edition = "2021"

[dependencies]
pulse_serialization = { workspace = true }
pulse_proc_macro = { workspace = true }
pulse_name = { workspace = true }

lol_alloc = "0.4.1"

[profile.release]
panic = "abort"