[package]
name = "pulse_token"
version = "0.1.0"
edition = "2021"

[dependencies]
pulse_cdt = { workspace = true }
wasm-snip = "0.4.0"

[lib]
crate-type = ["cdylib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"